<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * The course archiving script.
 *
 * @author     Anthony Radziszewski radzisze@ualberta.ca
 * @package    local/eclass/archive
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/*
 * Given .csv file of courses to be archived (generated by
 * archive_course_lists.php), it archives the courses not flagged for opt-out.
 * Suggested usage:
 * $ php $argv[0] <server> <webservice_token> <csvfile> <categoryid>
 * Test with:
 * $ php $argv[0] <server> <webservice_token> <csvfile> <categoryid> -n
 */

if ($argc != 5 && $argc != 6) {
    echo "Usage: php $argv[0] <server> <webservice_token> <csvfile> <categoryid>\n";
    echo "e.g.: php $argv[0] https://eclass-dev.srv.ualberta.ca 35ccac64ccde335ace2c246557482d32 2 1\n";
    echo "Token can be found in Moodle under:\n";
    echo " Site administration / Plugins / Web services / Manage tokens.\n";
}

$serverurl = $argv[1];
$token = $argv[2];
$csvfile = $argv[3];
$categoryid = $argv[4];

$functionname = 'local_ws_update_course_category';
$webserviceurl = $serverurl . '/webservice/rest/server.php?wstoken=' . $token . '&wsfunction=' . $functionname;

define('CLI_SCRIPT', true);
define('CACHE_DISABLE_ALL', true); // This prevents reading of existing caches.
define('IGNORE_COMPONENT_CACHE', true);

$file = fopen($csvfile, "r");
$line = fgets($file);
$line = rtrim($line);

if ($line == '') {
    echo "Please supply an archive list as input.\n";
    echo "Usage: php archive_courses.php https://eclass-dev.srv.ualberta.ca token archive-list.csv categoryid\n";
    die;
}

if ($line != "Course ID,Course shortname,Course fullname,First name(s),Last name(s),".
    "Email(s),CCIDs,Opt-Out flag") {
    echo "Input does not seem to be a valid archive course list.  Has the format changed?\n";
    die;
}

require_once(dirname(__FILE__) . '/curl.php');
$curl = new curl;

while ($line = fgets($file)) {
    $fields = array();
    $fields = str_getcsv($line);
    $courseid = $fields[0];
    $optout = $fields[7];

    if ($optout === '') {
        echo "Moving course $courseid to category $categoryid.\n";

        if (isset($argv[4]) && ($argv[5] != '-n')) {
            $parameters = array('courseid' => $courseid, 'categoryid' => $categoryid);
            $result = $curl->post($webserviceurl, $parameters);
            echo $result;
            if ($curl->error) {
                echo 'Error: ' . $curl->error_code . ': ' . $curl->error_message;
            }
        }
    }
    // You can view the full output using var_dump($curl->response).
}




